-- mMarkoweButy / OLX integration schema
-- REVIEW BEFORE APPLYING TO PRODUCTION.

create table if not exists public.olx_adverts (
  id bigint generated by default as identity primary key,
  product_id text not null,
  variant_id text,
  external_id text not null unique,
  olx_advert_id bigint unique,
  olx_url text,
  status text not null default 'draft',
  draft_payload jsonb,
  last_error jsonb,
  approved_at timestamptz,
  published_at timestamptz,
  last_synced_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists olx_adverts_product_id_idx on public.olx_adverts(product_id);
create index if not exists olx_adverts_status_idx on public.olx_adverts(status);

create table if not exists public.olx_operation_log (
  id bigint generated by default as identity primary key,
  external_id text,
  olx_advert_id bigint,
  operation text not null,
  outcome text not null,
  http_status integer,
  request_id text,
  details jsonb,
  created_at timestamptz not null default now()
);

create index if not exists olx_operation_log_external_id_idx on public.olx_operation_log(external_id);
create index if not exists olx_operation_log_created_at_idx on public.olx_operation_log(created_at desc);

alter table public.olx_adverts enable row level security;
alter table public.olx_operation_log enable row level security;

-- Intentionally no public policies.
-- Access is reserved for trusted server-side code/service role.
-- OAuth tokens/client secrets MUST NOT be stored in these tables in plaintext.
