import { createClient } from 'npm:@supabase/supabase-js@2';
import { handleCustomerAuth, customerSession } from './customer-auth.ts';

const FN='/functions/v1/markowe-buty';
const enc=new TextEncoder();
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});

function routePath(req){let p=new URL(req.url).pathname.replace(/\/{2,}/g,'/')||'/';for(const prefix of [FN,'/markowe-buty']){if(p===prefix||p===prefix+'/')return '/';if(p.startsWith(prefix+'/'))return p.slice(prefix.length)||'/'}return p}
function envKey(){let key='';const modern=Deno.env.get('SUPABASE_SECRET_KEYS');if(modern){try{key=JSON.parse(modern)?.default||''}catch{}}if(!key)key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';return key}
function adminClient(){const url=Deno.env.get('SUPABASE_URL');const key=envKey();if(!url||!key)throw new Error('SUPABASE_CONFIG_MISSING');return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}})}
function bytesToHex(a){return [...a].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function sha256(s){return bytesToHex(new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(s))))}
function randomB64(bytes=24){const a=new Uint8Array(bytes);crypto.getRandomValues(a);let s='';for(const b of a)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
async function pbkdf2(password,salt,iterations){const key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:enc.encode(salt),iterations},key,256);return bytesToHex(new Uint8Array(bits))}
function safeEq(a,b){if(a.length!==b.length)return false;let n=0;for(let i=0;i<a.length;i++)n|=a.charCodeAt(i)^b.charCodeAt(i);return n===0}
function getImages(x){const arr=Array.isArray(x?.image_urls)?x.image_urls.map(String).map(u=>u.trim()).filter(Boolean):[];if(!arr.length&&x?.image_url)arr.push(String(x.image_url));return [...new Set(arr)].slice(0,10)}
function clientIp(req){const x=req.headers.get('x-forwarded-for');return (x?.split(',')[0].trim()||req.headers.get('cf-connecting-ip')||'unknown').slice(0,128)}
async function clientKey(req){return sha256(clientIp(req)+'|'+(req.headers.get('user-agent')||'').slice(0,160))}
async function allowed(sb,req,bucket,limit,windowSeconds){const key=await clientKey(req);const {data,error}=await sb.rpc('hit_rate_limit',{p_bucket:bucket,p_key_hash:key,p_limit:limit,p_window_seconds:windowSeconds});if(error)throw error;return data===true}
function publicOrigin(req){const candidate=req.headers.get('origin')||'';try{const u=new URL(candidate);const h=u.hostname.toLowerCase();if(u.protocol==='https:'&&(h==='mmarkowebuty.pl'||h==='www.mmarkowebuty.pl'||h==='markowe-buty-marrkke93-2181.vercel.app'||(h.startsWith('markowe-buty-')&&h.endsWith('-marrkke93-2181.vercel.app'))))return u.origin}catch{}return 'https://www.mmarkowebuty.pl'}
function normalizeProduct(b){const brand=String(b.brand||'').trim(),name=String(b.name||'').trim();const price=Math.round(Number(String(b.price??'').replace(',','.'))*100);const oldRaw=String(b.oldPrice??'').trim();const oldPrice=oldRaw?Math.round(Number(oldRaw.replace(',','.'))*100):null;if(!brand||!name||!Number.isFinite(price)||price<=0)return{error:'Uzupełnij markę, nazwę i prawidłową cenę.'};if(oldRaw&&(!Number.isFinite(oldPrice)||oldPrice<=price))return{error:'Stara cena musi być wyższa od aktualnej ceny albo pole ma pozostać puste.'};const sizes=Array.isArray(b.sizes)?b.sizes.map(String).map(x=>x.trim()).filter(Boolean):String(b.sizes||'').split(',').map(x=>x.trim()).filter(Boolean);if(sizes.length!==1)return{error:'Jedna oferta odpowiada jednej fizycznej parze — podaj dokładnie jeden rozmiar.'};let images=Array.isArray(b.imageUrls)?b.imageUrls.map(String).map(u=>u.trim()).filter(Boolean):[];if(!images.length&&b.imageUrl)images=[String(b.imageUrl).trim()].filter(Boolean);images=[...new Set(images)].slice(0,10);return{row:{brand,name,description:String(b.description||'').trim(),sizes,price_cents:price,old_price_cents:oldPrice,image_url:images[0]||null,image_urls:images,published:b.published!==false,sold:!!b.sold,product_identifier:String(b.productIdentifier||'').trim()||null,manufacturer_name:String(b.manufacturerName||'').trim()||null,manufacturer_address:String(b.manufacturerAddress||'').trim()||null,manufacturer_email:String(b.manufacturerEmail||'').trim()||null,responsible_person_name:String(b.responsiblePersonName||'').trim()||null,responsible_person_address:String(b.responsiblePersonAddress||'').trim()||null,responsible_person_email:String(b.responsiblePersonEmail||'').trim()||null,safety_info:String(b.safetyInfo||'').trim()||null,material_upper:String(b.materialUpper||'').trim()||null,material_lining:String(b.materialLining||'').trim()||null,material_sole:String(b.materialSole||'').trim()||null}}}
async function referencePrices(sb,rows){if(!rows.length)return new Map();const ids=rows.map(x=>x.id);const {data}=await sb.from('product_price_history').select('product_id,price_cents,valid_from').in('product_id',ids).order('valid_from',{ascending:false});const by=new Map();for(const h of data||[]){if(!by.has(h.product_id))by.set(h.product_id,[]);by.get(h.product_id).push(h)}const out=new Map();for(const p of rows){const hist=by.get(p.id)||[];if(hist.length<2)continue;const latest=new Date(hist[0].valid_from).getTime(),cutoff=latest-30*864e5;const prev=hist.slice(1).filter(h=>new Date(h.valid_from).getTime()>=cutoff);if(prev.length){const min=Math.min(...prev.map(h=>h.price_cents));if(min>p.price_cents)out.set(p.id,min)}}return out}
async function fulfillSession(sb,s){const orderId=s.metadata?.order_id||s.client_reference_id;if(!orderId)return false;const addr=s.collected_information?.shipping_details?.address||s.shipping_details?.address||s.customer_details?.address||null;const {data,error}=await sb.rpc('finalize_paid_order',{p_order_id:orderId,p_email:s.customer_details?.email||null,p_phone:s.customer_details?.phone||null,p_name:s.customer_details?.name||null,p_shipping_address:addr});if(error)throw error;return data===true}
async function proxyInpost(req,innerPath){const url=Deno.env.get('SUPABASE_URL');if(!url)throw new Error('SUPABASE_URL_MISSING');const headers={'content-type':req.headers.get('content-type')||'application/json'};const auth=req.headers.get('authorization');if(auth)headers.authorization=auth;const init={method:req.method,headers};if(!['GET','HEAD'].includes(req.method))init.body=await req.text();const r=await fetch(`${url}/functions/v1/mmarkowebuty-inpost${innerPath}`,init);return new Response(await r.arrayBuffer(),{status:r.status,headers:{'content-type':r.headers.get('content-type')||'application/json; charset=utf-8','cache-control':'no-store'}})}
async function proxyAdminSettings(req){const url=Deno.env.get('SUPABASE_URL');if(!url)throw new Error('SUPABASE_URL_MISSING');const headers={'content-type':req.headers.get('content-type')||'application/json'};const auth=req.headers.get('authorization');if(auth)headers.authorization=auth;const init={method:req.method,headers};if(!['GET','HEAD'].includes(req.method))init.body=await req.text();const r=await fetch(`${url}/functions/v1/mmarkowebuty-admin-settings-api`,init);return new Response(await r.arrayBuffer(),{status:r.status,headers:{'content-type':r.headers.get('content-type')||'application/json; charset=utf-8','cache-control':'no-store'}})}


Deno.serve(async(req)=>{const p=routePath(req);try{
  if(p==='/api/customer-auth')return handleCustomerAuth(req);
  if(req.method==='OPTIONS')return new Response(null,{status:204,headers:{'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,PUT,DELETE,OPTIONS','access-control-allow-headers':'content-type,authorization'}});

  if(p==='/api/inpost/public-config'&&req.method==='GET')return proxyInpost(req,'/public-config');
  if(p==='/api/inpost/attach-point'&&req.method==='POST')return proxyInpost(req,'/attach-point');
  if(p==='/api/inpost/admin-settings'&&(req.method==='GET'||req.method==='PUT'))return proxyInpost(req,'/admin-settings');

  const sb=adminClient();
  if(p==='/api/health'&&req.method==='GET'){const{data,error}=await sb.from('admin_config').select('id').eq('id',1).maybeSingle();return json({ok:!error,adminConfig:!!data,errorCode:error?.code||null},error?500:200)}

  if(p==='/api/store-config'&&req.method==='GET'){const{data,error}=await sb.from('store_settings').select('store_name,legal_name,nip,regon,address_line,postal_code,city,country_code,customer_email,customer_phone,website_url,returns_address,shipping_method_name,shipping_price_cents,free_shipping_threshold_cents').eq('id',1).single();if(error)throw error;return json({storeName:data.store_name,legalName:data.legal_name,nip:data.nip,regon:data.regon,address:[data.address_line,data.postal_code,data.city].filter(Boolean).join(', '),countryCode:data.country_code,customerEmail:data.customer_email,customerPhone:data.customer_phone,websiteUrl:data.website_url,returnsAddress:data.returns_address,shipping:{method:data.shipping_method_name||'InPost Paczkomat',price:(data.shipping_price_cents||0)/100,freeFrom:(data.free_shipping_threshold_cents||0)/100}})}

  if(p==='/api/products'&&req.method==='GET'){await sb.rpc('cleanup_expired_reservations');const{data,error}=await sb.from('products').select('id,brand,name,description,sizes,price_cents,old_price_cents,image_url,image_urls,product_identifier,manufacturer_name,manufacturer_address,manufacturer_email,responsible_person_name,responsible_person_address,responsible_person_email,safety_info,material_upper,material_lining,material_sole').eq('published',true).eq('sold',false).or(`reserved_until.is.null,reserved_until.lt.${new Date().toISOString()}`).order('created_at',{ascending:false});if(error)throw error;const refs=await referencePrices(sb,data||[]);return json({products:(data||[]).map(x=>{const images=getImages(x),ref=refs.get(x.id);return{id:x.id,brand:x.brand,name:x.name,description:x.description||'',sizes:x.sizes||[],price:x.price_cents/100,oldPrice:x.old_price_cents?x.old_price_cents/100:null,referencePrice:ref?ref/100:null,imageUrl:images[0]||null,imageUrls:images,productIdentifier:x.product_identifier||null,manufacturerName:x.manufacturer_name||null,manufacturerAddress:x.manufacturer_address||null,manufacturerEmail:x.manufacturer_email||null,responsiblePersonName:x.responsible_person_name||null,responsiblePersonAddress:x.responsible_person_address||null,responsiblePersonEmail:x.responsible_person_email||null,safetyInfo:x.safety_info||null,materials:{upper:x.material_upper||null,lining:x.material_lining||null,sole:x.material_sole||null}}})})}

  if(p==='/api/admin/setup-status'&&req.method==='GET'){const{data,error}=await sb.from('admin_config').select('password_hash').eq('id',1).single();if(error)return json({error:'Nie udało się odczytać konfiguracji administratora.',code:error.code},500);return json({needsSetup:!data?.password_hash})}
  if(p==='/api/admin/setup'&&req.method==='POST'){if(!(await allowed(sb,req,'admin-setup',5,3600)))return json({error:'Zbyt wiele prób. Spróbuj później.'},429);const body=await req.json().catch(()=>({})),password=String(body.password||'');if(password.length<10)return json({error:'Hasło musi mieć co najmniej 10 znaków.'},400);if(password.length>200)return json({error:'Hasło jest zbyt długie.'},400);const{data,error:readError}=await sb.from('admin_config').select('password_hash').eq('id',1).single();if(readError)return json({error:'Nie udało się odczytać konfiguracji administratora.',code:readError.code},500);if(data?.password_hash)return json({error:'Panel administratora jest już skonfigurowany.'},409);const iterations=210000,salt=randomB64(24),hash=await pbkdf2(password,salt,iterations);const{error}=await sb.from('admin_config').update({password_hash:hash,password_salt:salt,password_iterations:iterations,updated_at:new Date().toISOString()}).eq('id',1);if(error)return json({error:'Nie udało się zapisać hasła administratora.',code:error.code},500);return json({ok:true})}
  if(p==='/api/admin/login'&&req.method==='POST'){if(!(await allowed(sb,req,'admin-login',8,900)))return json({error:'Zbyt wiele prób logowania. Spróbuj za kilka minut.'},429);const body=await req.json().catch(()=>({})),password=String(body.password||'');const{data,error}=await sb.from('admin_config').select('password_hash,password_salt,password_iterations').eq('id',1).single();if(error)return json({error:'Nie udało się odczytać konfiguracji administratora.',code:error.code},500);if(!data?.password_hash)return json({error:'Najpierw utwórz panel administratora.'},409);const candidate=data.password_salt?await pbkdf2(password,data.password_salt,Number(data.password_iterations)||210000):await sha256(password);if(!safeEq(candidate,String(data.password_hash)))return json({error:'Nieprawidłowe hasło.'},401);const token=randomB64(32),expiresAt=new Date(Date.now()+7*864e5).toISOString();await sb.from('admin_sessions').delete().lt('expires_at',new Date().toISOString());const{error:insertError}=await sb.from('admin_sessions').insert({token_hash:await sha256(token),expires_at:expiresAt});if(insertError)return json({error:'Nie udało się utworzyć sesji administratora.',code:insertError.code},500);return json({ok:true,token,expiresAt})}
  const adminToken=()=>{const h=req.headers.get('authorization')||'';return h.startsWith('Bearer ')?h.slice(7):''};
  const isAdmin=async()=>{const token=adminToken();if(!token)return false;const{data,error}=await sb.from('admin_sessions').select('expires_at').eq('token_hash',await sha256(token)).maybeSingle();return !error&&!!data&&new Date(data.expires_at)>new Date()};
  if(p==='/api/admin/session'&&req.method==='GET')return json({authenticated:await isAdmin()});
  if(p==='/api/admin/logout'&&req.method==='POST'){const token=adminToken();if(token)await sb.from('admin_sessions').delete().eq('token_hash',await sha256(token));return json({ok:true})}

  if(p.startsWith('/api/admin/')){
    if(!(await isAdmin()))return json({error:'Brak autoryzacji.'},401);
    if(p==='/api/admin/settings'&&(req.method==='GET'||req.method==='PUT'))return proxyAdminSettings(req);
    if(p==='/api/admin/products'&&req.method==='GET'){const{data,error}=await sb.from('products').select('*').order('created_at',{ascending:false});if(error)throw error;return json({products:(data||[]).map(x=>{const images=getImages(x);return{id:x.id,brand:x.brand,name:x.name,description:x.description||'',sizes:x.sizes||[],price:x.price_cents/100,oldPrice:x.old_price_cents?x.old_price_cents/100:null,imageUrl:images[0]||null,imageUrls:images,published:x.published,sold:x.sold,productIdentifier:x.product_identifier||'',manufacturerName:x.manufacturer_name||'',manufacturerAddress:x.manufacturer_address||'',manufacturerEmail:x.manufacturer_email||'',responsiblePersonName:x.responsible_person_name||'',responsiblePersonAddress:x.responsible_person_address||'',responsiblePersonEmail:x.responsible_person_email||'',safetyInfo:x.safety_info||'',materialUpper:x.material_upper||'',materialLining:x.material_lining||'',materialSole:x.material_sole||''}})})}
    if(p==='/api/admin/products'&&req.method==='POST'){const z=normalizeProduct(await req.json().catch(()=>({})));if(z.error)return json({error:z.error},400);const{data,error}=await sb.from('products').insert(z.row).select('id').single();if(error)throw error;return json({ok:true,id:data.id},201)}
    const pm=p.match(/^\/api\/admin\/products\/(\d+)$/);
    if(pm&&req.method==='PUT'){const z=normalizeProduct(await req.json().catch(()=>({})));if(z.error)return json({error:z.error},400);const{error}=await sb.from('products').update({...z.row,updated_at:new Date().toISOString()}).eq('id',Number(pm[1]));if(error)throw error;return json({ok:true})}
    if(pm&&req.method==='DELETE'){const id=Number(pm[1]);const{data}=await sb.from('products').select('sold,reserved_until').eq('id',id).maybeSingle();if(data?.sold)return json({error:'Sprzedanej oferty nie usuwamy — zachowujemy ją dla historii zamówień.'},409);if(data?.reserved_until&&new Date(data.reserved_until)>new Date())return json({error:'Oferta jest obecnie zarezerwowana przez klienta.'},409);const{error}=await sb.from('products').delete().eq('id',id);if(error)throw error;return json({ok:true})}
    if(p==='/api/admin/upload'&&req.method==='POST'){const fd=await req.formData(),f=fd.get('file');if(!(f instanceof File))return json({error:'Nie wybrano zdjęcia.'},400);if(f.size>5*1024*1024)return json({error:'Zdjęcie może mieć maksymalnie 5 MB.'},400);if(!['image/jpeg','image/png','image/webp'].includes(f.type))return json({error:'Dozwolone są zdjęcia JPG, PNG i WEBP.'},400);const ext=f.type==='image/png'?'png':f.type==='image/webp'?'webp':'jpg',key=`products/${new Date().getUTCFullYear()}/${crypto.randomUUID()}.${ext}`;const{error}=await sb.storage.from('product-images').upload(key,f,{contentType:f.type,upsert:false,cacheControl:'3600'});if(error)throw error;const{data}=sb.storage.from('product-images').getPublicUrl(key);return json({url:data.publicUrl})}
    if(p==='/api/admin/orders'&&req.method==='GET'){const{data,error}=await sb.from('orders').select('*,order_items(*)').order('created_at',{ascending:false}).limit(300);if(error)throw error;return json({orders:data||[]})}
    const om=p.match(/^\/api\/admin\/orders\/([0-9a-fA-F-]+)\/fulfillment$/);
    if(om&&req.method==='PUT'){const b=await req.json().catch(()=>({}));const statuses=['new','processing','shipped','delivered','returned','refunded','cancelled','manual_review'];if(!statuses.includes(String(b.status)))return json({error:'Nieprawidłowy status realizacji.'},400);const patch={fulfillment_status:b.status,carrier:String(b.carrier||'').trim()||null,tracking_number:String(b.trackingNumber||'').trim()||null,updated_at:new Date().toISOString()};if(b.status==='shipped')patch.shipped_at=new Date().toISOString();if(b.status==='delivered')patch.delivered_at=new Date().toISOString();if(b.status==='refunded')patch.refunded_at=new Date().toISOString();const{error}=await sb.from('orders').update(patch).eq('id',om[1]);if(error)throw error;return json({ok:true})}
  }

  if(p==='/api/create-checkout-session'&&req.method==='POST'){
    if(!(await allowed(sb,req,'checkout-create',8,600)))return json({error:'Zbyt wiele prób rozpoczęcia płatności. Odczekaj kilka minut.'},429);
    const stripe=Deno.env.get('STRIPE_SECRET_KEY');if(!stripe)return json({error:'Płatności Stripe nie są jeszcze aktywowane.'},503);
    await sb.rpc('cleanup_expired_reservations');
    const body=await req.json().catch(()=>({}));const ids=[...new Set((body.productIds||[]).map(Number).filter(x=>Number.isInteger(x)&&x>0))];if(!ids.length)return json({error:'Koszyk jest pusty.'},400);if(ids.length>10)return json({error:'Za dużo pozycji w koszyku.'},400);
    const orderId=crypto.randomUUID(),stripeExpiresAt=new Date(Date.now()+1810*1000),dbReserveUntil=new Date(stripeExpiresAt.getTime()+120*1000);
    const{data:ps,error:reserveError}=await sb.rpc('create_checkout_order_atomic',{p_order_id:orderId,p_product_ids:ids,p_reserve_until:dbReserveUntil.toISOString()});if(reserveError){const m=String(reserveError.message||'');if(m.includes('PRODUCT_UNAVAILABLE'))return json({error:'Jedna z par została właśnie zarezerwowana lub sprzedana. Odśwież koszyk.'},409);throw reserveError}
    const{data:order,error:orderError}=await sb.from('orders').select('shipping_method,shipping_amount_cents,amount_cents').eq('id',orderId).single();if(orderError){await sb.rpc('release_order_reservation',{p_order_id:orderId,p_status:'cancelled'});throw orderError}
    let customerUser=null;const customerAuth=req.headers.get('authorization')||(customerSession(req)?.access_token?'Bearer '+customerSession(req).access_token:'');if(customerAuth.startsWith('Bearer ')){try{const{data:userData}=await sb.auth.getUser(customerAuth.slice(7));customerUser=userData?.user||null;if(customerUser){await sb.from('orders').update({customer_user_id:customerUser.id}).eq('id',orderId)}}catch{}}
    const origin=publicOrigin(req),q=new URLSearchParams();q.set('mode','payment');q.set('locale','pl');q.set('expires_at',String(Math.floor(stripeExpiresAt.getTime()/1000)));q.set('success_url',`${origin}/?payment=success&session_id={CHECKOUT_SESSION_ID}`);q.set('cancel_url',`${origin}/?cancelled=1`);q.set('client_reference_id',orderId);q.set('metadata[order_id]',orderId);q.set('payment_intent_data[metadata][order_id]',orderId);q.set('shipping_address_collection[allowed_countries][0]','PL');q.set('phone_number_collection[enabled]','true');if(customerUser?.email)q.set('customer_email',customerUser.email);
    (ps||[]).forEach((x,i)=>{q.set(`line_items[${i}][quantity]`,'1');q.set(`line_items[${i}][price_data][currency]`,'pln');q.set(`line_items[${i}][price_data][unit_amount]`,String(x.price_cents));q.set(`line_items[${i}][price_data][product_data][name]`,`${x.brand} ${x.name}`.trim())});
    q.set('shipping_options[0][shipping_rate_data][type]','fixed_amount');q.set('shipping_options[0][shipping_rate_data][fixed_amount][amount]',String(order.shipping_amount_cents||0));q.set('shipping_options[0][shipping_rate_data][fixed_amount][currency]','pln');q.set('shipping_options[0][shipping_rate_data][display_name]',String(order.shipping_method||'InPost Paczkomat'));
    const r=await fetch('https://api.stripe.com/v1/checkout/sessions',{method:'POST',headers:{authorization:`Bearer ${stripe}`,'content-type':'application/x-www-form-urlencoded','Idempotency-Key':'checkout-'+orderId},body:q.toString()});const s=await r.json();if(!r.ok){await sb.rpc('release_order_reservation',{p_order_id:orderId,p_status:'cancelled'});return json({error:s?.error?.message||'Stripe odrzucił utworzenie płatności.'},400)}
    const{error:updateError}=await sb.from('orders').update({stripe_session_id:s.id,updated_at:new Date().toISOString()}).eq('id',orderId);if(updateError){await fetch(`https://api.stripe.com/v1/checkout/sessions/${encodeURIComponent(s.id)}/expire`,{method:'POST',headers:{authorization:`Bearer ${stripe}`}}).catch(()=>{});await sb.rpc('release_order_reservation',{p_order_id:orderId,p_status:'cancelled'});throw updateError}
    return json({url:s.url,sessionId:s.id,expiresAt:stripeExpiresAt.toISOString(),shippingAmount:(order.shipping_amount_cents||0)/100,total:(order.amount_cents||0)/100})
  }

  if(p==='/api/checkout/verify'&&req.method==='GET'){const stripe=Deno.env.get('STRIPE_SECRET_KEY');if(!stripe)return json({error:'Stripe nieaktywny.'},503);const sid=new URL(req.url).searchParams.get('session_id');if(!sid)return json({error:'Brak identyfikatora płatności.'},400);const r=await fetch(`https://api.stripe.com/v1/checkout/sessions/${encodeURIComponent(sid)}`,{headers:{authorization:`Bearer ${stripe}`}}),s=await r.json();if(!r.ok)return json({error:s?.error?.message||'Nie udało się sprawdzić płatności.'},400);if(s.payment_status==='paid')await fulfillSession(sb,s);return json({paymentStatus:s.payment_status,orderId:s.metadata?.order_id||s.client_reference_id})}

  return json({error:'Nie znaleziono endpointu.',path:p},404)
}catch(e){console.error('mMarkoweButy',p,e);return json({error:'Wewnętrzny błąd serwera.',code:e instanceof Error?e.message:'UNKNOWN'},500)}});

