plugins { id 'com.android.application' }
android {
    namespace 'pl.marek.zlomiarz'
    compileSdk 35
    defaultConfig {
        applicationId 'pl.marek.zlomiarz'
        minSdk 26
        targetSdk 35
        versionCode 5
        versionName '0.4.0'
    }
    buildTypes { release { minifyEnabled false } }
    compileOptions { sourceCompatibility JavaVersion.VERSION_1_8; targetCompatibility JavaVersion.VERSION_1_8 }
}
